### ISSUE TITLE
x,y coordinates vs y,x coordinates

### ISSUE THREAD

**Issue by bardec** [JohnLZeller/climyadmin#1]
Hey John!

Thanks again for everything, I feel like a real piece of shit. Anywhooo I'm trying to get acquainted to the codebase (which is very clean by the way), and I'm working on adding a database selector for the first menu option. 

Along the way I was noticing you were comparing x's and y's, and I was just wondering if there was a reason for that. I know that curses made the mistake of dealing in y's and x's, but you seem to be addressing those values to x's and y's. I found an example [here](https://github.com/JohnLZeller/climyadmin/blob/master/main.py#L124).

If there is no reason that's cool, it was an interview so I'm sure you were just kicking code out! Just wondering if you had a reason for what is otherwise an odd choice haha.

**Comment by JohnLZeller** [comment]
I really have no clue here, it seems like it has something to do with the scrolling effect I was going for, but I am really not sure haha

**Comment by bardec** [comment]
haha no problem, curses is just weird and does y,x instead of x,y.. scanlines or something grumble grumble. Thanks!

**Comment by JohnLZeller** [comment]
np!
