### ISSUE TITLE
Global Variable Location

### ISSUE THREAD

**Issue by VenomousWyvern241** [JohnLZeller/climyadmin#14]
![image](https://cloud.githubusercontent.com/assets/11916129/8812870/9d411876-2fb3-11e5-8bbf-b76e782b389f.png)

I had to move the two global variables shown above to line 24 and 25 in order too fix the following error:

![image](https://cloud.githubusercontent.com/assets/11916129/8812911/e56d4b56-2fb3-11e5-9a9f-eb66c80da8e1.png)

After making this change the code functioned as it should, taking me to the main menu of cliMyAdmin.

**Comment by JohnLZeller** [comment]
No need to add globals. You forgot to add "curses." before ALT_KEY_ENTER

**Comment by bardec** [comment]
So actually its a little different. curses.KEY_ENTER is 343, but my keyboard uses 10 for enter. So not the same thing curiously enough!

**Comment by bardec** [comment]
I guess the curses.KEY_ENTER is the **numeric** key enter.

**Comment by VenomousWyvern241** [comment]
Oh ok ill have to change that when I commit again... just saw these sorry...

**Comment by bardec** [comment]
Yeah you can move it outside the module or just change it to `self.ALT_KEY_ENTER` which is what I'm doing :)
