### ISSUE TITLE
Selection of database and display of tables

### ISSUE THREAD

**Issue by JohnLZeller** [JohnLZeller/climyadmin#4]

**Comment by bardec** [comment]
So right now I have this as specifying a database URL from the sqlalchemy doc:

> The string form of the URL is dialect[+driver]://user:password@host/dbname[?key=value..], where dialect is a database name such as mysql, oracle, postgresql, etc., and driver the name of a DBAPI, such as psycopg2, pyodbc, cx_oracle, etc. Alternatively, the URL can be an instance of URL.

This is what we want yes?

**Comment by JohnLZeller** [comment]
I think what we actually want is to have a list of available databases from the server to pick from. Then the code can insert that database name into the URL for sqlalchemy to open it up.

There will probably be a command line arg that takes in the URL for the sql server, with the auth added as well. That'll make sure we have the access info to grab the list of databases.

**Comment by bardec** [comment]
Ah okay cool, thanks for clearing that up. I came across these [docs](http://docs.sqlalchemy.org/en/rel_0_9/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_schema_names) in that case. Looks like using the Inspector class is what we want then.

**Comment by bardec** [comment]
So to list the actual dbs we need to go outside of sqlalchemy, do you all have any recommendations? I am looking at [fabric](http://www.fabfile.org) for opening a remote connection and running psql --list/whatever mysql uses. 

Or even better -- [paramiko](https://github.com/paramiko/paramiko) which is what fabric uses internally.

**Comment by bardec** [comment]
Disregard stupid library questions, psql can do remote connection by itself!
